// <auto-generated />
using System;
using Gloria.Commission.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gloria.Commission.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommissionDbContext))]
    [Migration("20260910072828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc")
                        .HasDatabaseName("idx_audit_logs_changed_at_utc");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("idx_audit_logs_entity_name_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalesBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("uq_commission_results_period_id_employee_id");

                    b.ToTable("commission_results", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionResultLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AppliedFixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AppliedRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("CommissionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SaleRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommissionResultId");

                    b.HasIndex("CommissionRuleId");

                    b.HasIndex("SaleRecordId");

                    b.ToTable("commission_result_lines", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotel")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MultiplyByQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGroup")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TierApplication")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_commission_rules_code");

                    b.HasIndex("IsActive", "EffectiveFrom")
                        .HasDatabaseName("idx_commission_rules_is_active_effective_from");

                    b.ToTable("commission_rules", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionRuleTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommissionRuleId", "MinAmount")
                        .HasDatabaseName("idx_commission_rule_tiers_rule_id_min_amount");

                    b.ToTable("commission_rule_tiers", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_departments_code");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasDatabaseName("uq_employees_employee_no");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicateRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("idx_import_batches_file_hash");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.ImportError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("import_errors", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_periods_year_month");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_products_code");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.SaleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountTry")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotel")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outlet")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReversedSaleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ReversedSaleId");

                    b.HasIndex("SourceHash")
                        .IsUnique()
                        .HasDatabaseName("uq_sale_records_source_hash");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("idx_sale_records_transaction_date");

                    b.HasIndex("EmployeeNo", "TransactionDate")
                        .HasDatabaseName("idx_sale_records_employee_no_transaction_date");

                    b.ToTable("sale_records", (string)null);
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionResult", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gloria.Commission.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionResultLine", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.CommissionResult", "CommissionResult")
                        .WithMany("Lines")
                        .HasForeignKey("CommissionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gloria.Commission.Domain.Entities.CommissionRule", "CommissionRule")
                        .WithMany()
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gloria.Commission.Domain.Entities.SaleRecord", "SaleRecord")
                        .WithMany()
                        .HasForeignKey("SaleRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionResult");

                    b.Navigation("CommissionRule");

                    b.Navigation("SaleRecord");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionRuleTier", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.CommissionRule", "CommissionRule")
                        .WithMany("Tiers")
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionRule");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.ImportError", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.SaleRecord", b =>
                {
                    b.HasOne("Gloria.Commission.Domain.Entities.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gloria.Commission.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gloria.Commission.Domain.Entities.SaleRecord", "ReversedSale")
                        .WithMany()
                        .HasForeignKey("ReversedSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("ImportBatch");

                    b.Navigation("ReversedSale");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionResult", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.CommissionRule", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Gloria.Commission.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
